services:
  Plugins\FreePlanLimit\Bootstrap:
    public: true

  Plugins\FreePlanLimit\EventListener\FreePlanServerLimitListener:
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: kernel.event_subscriber }
